// <auto-generated />
using System;
using ApiBabterStyle.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApiBabterStyle.Migrations
{
    [DbContext(typeof(BarberShopDbContext))]
    partial class BarberShopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApiBabterStyle.Model.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BarberId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MercadoPagoInitPoint")
                        .HasColumnType("text");

                    b.Property<string>("MercadoPagoPaymentId")
                        .HasColumnType("text");

                    b.Property<string>("MercadoPagoPreferenceId")
                        .HasColumnType("text");

                    b.Property<string>("MercadoPagoRefundId")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("UserId");

                    b.HasIndex("BarberId", "ScheduledAt");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("ApiBabterStyle.Model.Barber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Barbers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0d27f419-3cde-458f-90d1-1a2f9905a301"),
                            Active = true,
                            Name = "Carlos Silva",
                            Specialty = "Corte masculino e degradê"
                        },
                        new
                        {
                            Id = new Guid("8de280dd-f78c-4ed3-bb35-67820c03fb3d"),
                            Active = true,
                            Name = "Rafael Santos",
                            Specialty = "Barba, navalha e sobrancelha"
                        },
                        new
                        {
                            Id = new Guid("7ba716f3-2170-46d2-bb4e-bf6c983cfead"),
                            Active = true,
                            Name = "Ton Barber",
                            Specialty = "Corte masculino premium"
                        },
                        new
                        {
                            Id = new Guid("4c6f1905-a984-49f1-9129-c7b7c5c5eaf2"),
                            Active = true,
                            Name = "Michael Trindade",
                            Specialty = "Corte, barba e degradê"
                        },
                        new
                        {
                            Id = new Guid("75624c38-17fd-4720-8670-42a7a59f32db"),
                            Active = true,
                            Name = "Valdir Bispo",
                            Specialty = "Barba, navalha e finalização"
                        });
                });

            modelBuilder.Entity("ApiBabterStyle.Model.BarberService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = new Guid("82e9cfcb-0709-4e62-b7ce-7150e1c63583"),
                            Active = true,
                            Description = "Corte masculino completo",
                            DurationMinutes = 45,
                            Name = "Corte",
                            Price = 45m
                        },
                        new
                        {
                            Id = new Guid("fc39f0ec-a173-4f4c-9bf1-7d4ac4c64cd6"),
                            Active = true,
                            Description = "Barba com toalha quente e acabamento na navalha",
                            DurationMinutes = 30,
                            Name = "Barba",
                            Price = 35m
                        },
                        new
                        {
                            Id = new Guid("f89df8e5-84f4-491e-8edb-80105a9502a5"),
                            Active = true,
                            Description = "Pacote completo de corte e barba",
                            DurationMinutes = 75,
                            Name = "Corte + Barba",
                            Price = 75m
                        },
                        new
                        {
                            Id = new Guid("714f2a9f-f890-4592-bf37-56b3f5b913ef"),
                            Active = true,
                            Description = "Design discreto e natural",
                            DurationMinutes = 20,
                            Name = "Sobrancelha",
                            Price = 25m
                        },
                        new
                        {
                            Id = new Guid("f054bf3c-27c3-4374-b8c7-79acc4403590"),
                            Active = true,
                            Description = "Hidratacao e detox capilar",
                            DurationMinutes = 50,
                            Name = "Tratamento capilar",
                            Price = 85m
                        },
                        new
                        {
                            Id = new Guid("fe8385e9-0377-4907-9a8f-707e6d4a79f6"),
                            Active = true,
                            Description = "Experiencia reservada com cabelo, barba e acabamento",
                            DurationMinutes = 120,
                            Name = "Dia do noivo / experiencia premium",
                            Price = 240m
                        });
                });

            modelBuilder.Entity("ApiBabterStyle.Model.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ApiBabterStyle.Model.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ApiBabterStyle.Model.Appointment", b =>
                {
                    b.HasOne("ApiBabterStyle.Model.Barber", "Barber")
                        .WithMany("Appointments")
                        .HasForeignKey("BarberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiBabterStyle.Model.BarberService", "Service")
                        .WithMany("Appointments")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiBabterStyle.Model.User", "User")
                        .WithMany("Appointments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barber");

                    b.Navigation("Service");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ApiBabterStyle.Model.Barber", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("ApiBabterStyle.Model.BarberService", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("ApiBabterStyle.Model.User", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
